config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'books/bestsellers', :to => 'books#best_sellers'
  resources :books
  root 'books#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :name, presence: true
  validates :auther, presence: true
  validates :rating, inclusion: {in: 1..5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
    @five_star_books =Book.where(rating: 5)
    @four_star_books =Book.where(rating: 4)
    @three_star_books =Book.where(rating: 3)
    @two_star_books =Book.where(rating: 2)
    @one_star_books =Book.where(rating: 1)
  end


  def show
    @book = Book.find(params[:id])
  end


  def new
    @book = Book.new()
  end


  def create
    @book = Book.new(book_params)
    if @book.save
    redirect_to book_path(@book)
    else
      render :new
    end
  end


  def edit
    @book = Book.find(params[:id])
  end


  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    redirect_to book_path(@book)
  end


  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end


  def best_sellers
  end


  private

  def book_params
    params.require(:book).permit(:name, :auther, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/best_sellers.html.erb
<div class="container-flex">
  <h1 class="ml-5 mt-2">Top This Week</h1>
  <%= link_to 'Back to shelfs', books_path, class:'btn btn-danger ml-5 mt-2' %>
  <ul id="best_sellers_list">
  </ui>
</div>

<!-- script for fetch can be found in js/custom/best_sellers -->

<!--Note: can paste it here to test- needs API key -->

app/views/books/edit.html.erb
<div class="container add_book">
  <div class="">
    <div class="row justify-content-center">
      <div class="col-md-3 d-flex">
        <%= simple_form_for (@book) do |f| %>

         <div class="form-col book-form">
          <h2>Edit book</h2>
          <div class="col my-1">
            <%= f.label :name %>
            <%= f.text_field :name %>
          </div>

          <div class="col my-1">
            <%= f.label :auther %>
            <%= f.text_field :auther %>
          </div>

          <div class="col my-1">
            <%= f.label :rating %>
            <%= f.number_field :rating %>
           </div>

            <div class="col my-3">
              <%= f.submit %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<h1 class="ml-2 my-2" >Top Shelfs</h1>

<%= link_to 'Add Book ➕', new_book_path, class:'ml-3 mb-5 btn btn-primary' %>
<%= link_to 'See this weeks top 5 selling books 🔥', books_bestsellers_path,data: { turbolinks: false }, class:'ml-3 mb-5 btn btn-success' %>

<div class="">
  <div class="row">
    <div class="col-sm">
       <h2 class="ml-2">5 Star Books</h2>
      <div class="shelf five-shelf d-flex justify-content-between align-items-center m-1">
      <% @five_star_books.each do |book|%>

      <%= link_to (book) do %>
        <div class="book">
          <p> <%= book.name %><p>
          <p> <%= book.auther %></p>
        </div>
       <% end %>
      <% end %>
    </div>
  </div>
</div>

<div class="">
  <div class="row">
    <div class="col-sm">
       <h2 class="ml-2" >4 Star Books</h2>
      <div class="shelf four-shelf d-flex justify-content-between align-items-center m-1">
      <% @four_star_books.each do |book|%>

      <%= link_to (book) do %>
        <div class="book">
          <p> <%= book.name %><p>
          <p> <%= book.auther %></p>
        </div>
       <% end %>
      <% end %>
    </div>
  </div>
</div>

<div class="">
  <div class="row">
    <div class="col-sm">
       <h2 class="ml-2">3 Star Books</h2>
      <div class="shelf three-shelf d-flex justify-content-between align-items-center m-1">
      <% @three_star_books.each do |book|%>

      <%= link_to (book) do %>
        <div class="book">
          <p> <%= book.name %><p>
          <p> <%= book.auther %></p>
        </div>
       <% end %>
      <% end %>
    </div>
  </div>
</div>

</div>

app/views/books/new.html.erb
<div class="container add_book">
  <div class="">
    <div class="row justify-content-center">
      <div class="col-md-3 d-flex">
        <%= simple_form_for (@book) do |f| %>

         <div class="form-col book-form">
          <h2>Add a book</h2>
          <div class="col my-1">
            <%= f.label :name %>
            <%= f.text_field :name %>
          </div>

          <div class="col my-1">
            <%= f.label :auther %>
            <%= f.text_field :auther %>
          </div>

          <div class="col my-1">
            <%= f.label :rating %>
            <%= f.number_field :rating %>
           </div>

           <div class="col my-3">
              <%= f.submit %>
           </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<h2> <%= @book.name %> </h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= yield %>
  </body>
</html>